name: Deploy to Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_RESOURCE_REGION: ${{ vars.GCP_RESOURCE_REGION }}
  GCP_REGISTRY:  ${{ vars.GCP_REGISTRY }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build --build-arg MESSAGE_DB_VERSION=1.3.0 --build-arg POSTGRES_VERSION=16.1 -t ${{ env.IMAGE_NAME }} .

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCR_KEY }}'

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: "${{ env.GCP_RESOURCE_REGION }}-docker.pkg.dev"
          username: _json_key_base64
          password: ${{ secrets.GCR_KEY }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.GCP_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_NAME }} ${{ env.GCP_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.GCP_REGISTRY }}/${{ env.IMAGE_NAME }} --all-tags